"""fase 3 pipeline runs

Revision ID: a8913cfbabc8
Revises: 841865bad049
Create Date: 2026-06-29 04:04:36.398716

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a8913cfbabc8'
down_revision: str | None = '841865bad049'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'success', 'failed', name='pipeline_run_status'), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('pipeline_run_id', sa.UUID(), nullable=True))
    op.add_column('jobs', sa.Column('step_index', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'pipeline_runs', ['pipeline_run_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'step_index')
    op.drop_column('jobs', 'pipeline_run_id')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
